plugins { id 'com.android.application' }

android {
    namespace 'com.tiraz.admin'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tiraz.admin'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.3'
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets', '../../web/admin']
        }
    }
}