import {cors,json,admin,db,body,failure} from './shared.ts';
const groups:Record<string,string>={integrations:'owner',test_telegram:'owner',save_integrations:'owner',list_admins:'owner',invite_admin:'owner',update_admin:'owner',publish:'content',delete_media:'content',cover:'content',order_notes:'orders',retry_outbox:'owner'};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{if(req.method!=='POST')throw new Error('METHOD_NOT_ALLOWED');const b=await body(req),permission=groups[b.action];if(!permission)throw new Error('INVALID_ACTION');const {sb,user}=await admin(req,permission);let result:any={ok:true};
if(b.action==='integrations'){const [{data:channels},{data:c},{data:q}]=await Promise.all([sb.from('integration_channels').select('purpose,channel_id,enabled'),sb.from('integration_credentials').select('telegram_bot_token,onesignal_rest_key').eq('id',true).single(),sb.from('notification_outbox').select('id,kind,state,attempts,last_error').neq('state','sent').order('created_at',{ascending:false}).limit(30)]);result={ok:true,channels,bot_configured:!!c?.telegram_bot_token,onesignal_key_configured:!!c?.onesignal_rest_key,outbox:q};}
if(b.action==='save_integrations'){const update:any={id:true};if(b.telegram_bot_token)update.telegram_bot_token=String(b.telegram_bot_token).trim();if(b.onesignal_rest_key)update.onesignal_rest_key=String(b.onesignal_rest_key).trim();if(Object.keys(update).length>1){const {error}=await sb.from('integration_credentials').upsert(update);if(error)throw error}if(Array.isArray(b.channels)){const allowed=['product_images','product_videos','boxes','reviews','archive','logs','orders'];for(const ch of b.channels){if(!allowed.includes(ch.purpose)||ch.channel_id&&!/^-100\d+$/.test(ch.channel_id))throw new Error('INVALID_CHANNEL');const {error}=await sb.from('integration_channels').upsert({purpose:ch.purpose,channel_id:ch.channel_id||null,enabled:!!ch.channel_id&&!!ch.enabled});if(error)throw error}}}
if(b.action==='test_telegram'){const {data:c}=await sb.from('integration_credentials').select('telegram_bot_token').eq('id',true).single();if(!c?.telegram_bot_token)throw new Error('BOT_NOT_CONFIGURED');const call=async(method:string,params:Record<string,string>={})=>{const r=await fetch(`https://api.telegram.org/bot${c.telegram_bot_token}/${method}?${new URLSearchParams(params)}`,{signal:AbortSignal.timeout(10000)});return r.json()};const me=await call('getMe');if(!me.ok)throw new Error('BOT_INVALID');const {data:channels}=await sb.from('integration_channels').select('purpose,channel_id,enabled').eq('enabled',true);const checks=[];for(const ch of channels||[]){const m=await call('getChatMember',{chat_id:ch.channel_id,user_id:String(me.result.id)});checks.push({purpose:ch.purpose,ok:!!m.ok&&(m.result.status==='creator'||m.result.status==='administrator'&&m.result.can_post_messages!==false)})}result={ok:true,username:me.result.username,channels:checks};}
if(b.action==='publish'){if(b.published){const {count}=await sb.from('product_media').select('id',{count:'exact',head:true}).eq('product_id',b.id);if(!count)throw new Error('MEDIA_REQUIRED');const {count:vc}=await sb.from('product_variants').select('id',{count:'exact',head:true}).eq('product_id',b.id).eq('active',true);if(!vc)throw new Error('VARIANT_REQUIRED')}const {error}=await sb.from('products').update({published:!!b.published}).eq('id',b.id);if(error)throw error;}
if(b.action==='cover'){const {data:m}=await sb.from('product_media').select('product_id,media_type').eq('id',b.id).single();if(!m||m.media_type!=='image')throw new Error('IMAGE_REQUIRED');const {error:e1}=await sb.from('product_media').update({is_cover:false}).eq('product_id',m.product_id);if(e1)throw e1;const {error:e2}=await sb.from('product_media').update({is_cover:true}).eq('id',b.id);if(e2)throw e2;}
if(b.action==='delete_media'){const {data:m}=await sb.from('product_media').select('*').eq('id',b.id).single();if(!m)throw new Error('MEDIA_NOT_FOUND');const {data:c}=await sb.from('integration_credentials').select('telegram_bot_token').eq('id',true).single();if(m.telegram_message_id&&c?.telegram_bot_token){const r=await fetch(`https://api.telegram.org/bot${c.telegram_bot_token}/deleteMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:m.telegram_chat_id,message_id:m.telegram_message_id})});const j=await r.json();if(!j.ok&&!String(j.description).includes('message to delete not found'))throw new Error('DELETE_STORAGE_FAILED')};const {error}=await sb.from('product_media').delete().eq('id',b.id);if(error)throw error;}
if(b.action==='order_notes'){const {error}=await sb.from('orders').update({admin_notes:String(b.notes||'').slice(0,1000)}).eq('id',b.id);if(error)throw error;}
if(b.action==='list_admins'){const {data:a}=await sb.from('admin_users').select('user_id,role,active,created_at');result={ok:true,admins:a};}
if(b.action==='invite_admin'){if(!['admin','orders','content'].includes(b.role))throw new Error('INVALID_ROLE');const {data,error}=await sb.auth.admin.inviteUserByEmail(b.email,{redirectTo:'https://3c5-o.github.io/tiraz-store/admin/'});if(error)throw new Error('INVITE_FAILED');const {error:e}=await sb.from('admin_users').insert({user_id:data.user.id,role:b.role,active:true});if(e)throw e;}
if(b.action==='update_admin'){const {data:a}=await sb.from('admin_users').select('role').eq('user_id',b.id).single();if(!a||a.role==='owner'||!['admin','orders','content'].includes(b.role))throw new Error('OWNER_PROTECTED');const {error}=await sb.from('admin_users').update({role:b.role,active:!!b.active}).eq('user_id',b.id);if(error)throw error;}
if(b.action==='retry_outbox'){const {error}=await sb.from('notification_outbox').update({state:'pending',next_attempt:new Date().toISOString()}).eq('id',b.id).in('state',['failed','blocked']);if(error)throw error;}
if(!['integrations','test_telegram','list_admins'].includes(b.action))await sb.from('audit_log').insert({user_id:user.id,action:b.action,entity_id:String(b.id||''),details:{}});
return json(result);}catch(e){return failure(e)}});
