import {cors,db,identity} from './shared.ts';
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{if(!['GET','HEAD'].includes(req.method))return new Response('method',{status:405,headers:cors});const key=new URL(req.url).searchParams.get('key');if(!key)return new Response('missing',{status:400,headers:cors});const sb=db();let media:any=null,visible=false;
const {data:p}=await sb.from('product_media').select('telegram_file_id,content_type,media_type,product:products(published)').eq('proxy_key',key).maybeSingle();if(p){media=p;visible=!!p.product?.published}
if(!media){const {data:b}=await sb.from('boxes').select('telegram_file_id,active').eq('proxy_key',key).maybeSingle();if(b){media=b;visible=b.active}}
if(!media){const {data:r}=await sb.from('reviews').select('telegram_file_id,approved').eq('proxy_key',key).maybeSingle();if(r){media=r;visible=r.approved}}
if(!visible){const user=await identity(req).catch(()=>null);if(user){const {data:a}=await sb.from('admin_users').select('role,active').eq('user_id',user.id).maybeSingle();visible=!!a?.active&&['owner','admin','content'].includes(a.role)}}
if(!visible||!media?.telegram_file_id)return new Response('not found',{status:404,headers:cors});const {data:c}=await sb.from('integration_credentials').select('telegram_bot_token').eq('id',true).single();if(!c?.telegram_bot_token)return new Response('unavailable',{status:503,headers:cors});
const meta=await fetch(`https://api.telegram.org/bot${c.telegram_bot_token}/getFile?file_id=${encodeURIComponent(media.telegram_file_id)}`,{signal:AbortSignal.timeout(15000)});const mj=await meta.json();if(!mj.ok)return new Response('unavailable',{status:502,headers:cors});const source=await fetch(`https://api.telegram.org/file/bot${c.telegram_bot_token}/${mj.result.file_path}`,{signal:AbortSignal.timeout(30000)});if(!source.ok)return new Response('unavailable',{status:502,headers:cors});
const bytes=new Uint8Array(await source.arrayBuffer()),headers=new Headers({...cors,'Content-Type':media.content_type||(media.media_type==='video'?'video/mp4':'image/jpeg'),'Cache-Control':'private, max-age=60','Accept-Ranges':'bytes','X-Content-Type-Options':'nosniff','Access-Control-Expose-Headers':'Content-Range,Accept-Ranges,Content-Length'});let status=200,start=0,end=bytes.length-1;const range=req.headers.get('Range');if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range);if(!m||(!m[1]&&!m[2]))return new Response(null,{status:416,headers:{...cors,'Content-Range':`bytes */${bytes.length}`}});if(!m[1])start=Math.max(0,bytes.length-Number(m[2]));else{start=Number(m[1]);if(m[2])end=Math.min(end,Number(m[2]))}if(start>end||start>=bytes.length)return new Response(null,{status:416,headers:{...cors,'Content-Range':`bytes */${bytes.length}`}});status=206;headers.set('Content-Range',`bytes ${start}-${end}/${bytes.length}`)}headers.set('Content-Length',String(end-start+1));return new Response(req.method==='HEAD'?null:bytes.slice(start,end+1),{status,headers});
}catch{return new Response('unavailable',{status:502,headers:cors})}});
