import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-worker-key','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
export function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}})}
export function db(){return createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!)}
export async function identity(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return null;const {data,error}=await db().auth.getUser(token);if(error||!data.user)throw new Error('UNAUTHORIZED');return data.user;}
export async function admin(req:Request,permission:string){const sb=db(),user=await identity(req);if(!user)throw new Error('UNAUTHORIZED');const {data:a}=await sb.from('admin_users').select('role,active').eq('user_id',user.id).maybeSingle();const allowed=a?.active&&(a.role==='owner'||a.role===permission||(a.role==='admin'&&['content','orders','settings','audit'].includes(permission)));if(!allowed)throw new Error('FORBIDDEN');return {sb,user,role:a.role};}
export async function limit(req:Request,action:string,max=30,seconds=60){const ip=req.headers.get('x-forwarded-for')?.split(',')[0]||req.headers.get('cf-connecting-ip')||'unknown';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(action+ip));const key=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');const {data,error}=await db().rpc('consume_api_limit',{p_key:key,p_limit:max,p_seconds:seconds});if(error||!data)throw new Error('RATE_LIMIT');}
export function failure(e:unknown){const message=e instanceof Error?e.message:'SERVER_ERROR';return json({error:message},message==='FORBIDDEN'?403:message==='UNAUTHORIZED'?401:message==='RATE_LIMIT'?429:400)}
export async function body(req:Request){if(Number(req.headers.get('content-length')||0)>64000)throw new Error('PAYLOAD_TOO_LARGE');const text=await req.text();if(text.length>64000)throw new Error('PAYLOAD_TOO_LARGE');return JSON.parse(text)}
