import {cors,json,admin,failure} from './shared.ts';
const MAX=20*1024*1024;
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);const {sb}=await admin(req,'content');if(Number(req.headers.get('content-length')||0)>MAX+65536)throw new Error('FILE_TOO_LARGE');
const form=await req.formData(),file=form.get('file');if(!(file instanceof File)||file.size===0||file.size>MAX)throw new Error('FILE_TOO_LARGE');if(!/^(image\/(jpeg|png|webp|gif)|video\/(mp4|webm|quicktime))$/.test(file.type))throw new Error('UNSUPPORTED_FILE');
const entity=String(form.get('entity_type')||'product');if(!['product','box','review'].includes(entity))throw new Error('INVALID_ENTITY');const table=entity==='box'?'boxes':entity==='review'?'reviews':'products',id=String(form.get(entity==='box'?'box_id':entity==='review'?'review_id':'product_id')||'');
const {data:target}=await sb.from(table).select('id').eq('id',id).maybeSingle();if(!target)throw new Error('ENTITY_NOT_FOUND');const variant=String(form.get('variant_id')||'');if(entity==='product'&&variant){const {data:v}=await sb.from('product_variants').select('id').eq('id',variant).eq('product_id',id).maybeSingle();if(!v)throw new Error('Variant unavailable')};const purpose=entity==='box'?'boxes':entity==='review'?'reviews':file.type.startsWith('video/')?'product_videos':'product_images';
const [{data:cred},{data:channel}]=await Promise.all([sb.from('integration_credentials').select('telegram_bot_token').eq('id',true).single(),sb.from('integration_channels').select('channel_id,enabled').eq('purpose',purpose).maybeSingle()]);
if(!cred?.telegram_bot_token)throw new Error('BOT_NOT_CONFIGURED');if(!channel?.enabled||!channel.channel_id)throw new Error('CHANNEL_NOT_CONFIGURED');
const fd=new FormData();fd.append('chat_id',channel.channel_id);fd.append('document',file,file.name);
const r=await fetch(`https://api.telegram.org/bot${cred.telegram_bot_token}/sendDocument`,{method:'POST',body:fd,signal:AbortSignal.timeout(90000)}),j=await r.json();if(!j.ok)throw new Error('TELEGRAM_UPLOAD_FAILED');
const fields={telegram_file_id:j.result.document.file_id,telegram_message_id:j.result.message_id,telegram_chat_id:String(channel.channel_id)};
let result;
if(entity==='product'){const {count}=await sb.from('product_media').select('id',{count:'exact',head:true}).eq('product_id',id);result=await sb.from('product_media').insert({...fields,product_id:id,variant_id:variant||null,media_type:file.type.startsWith('video/')?'video':'image',content_type:file.type,file_size:file.size,file_name:file.name,sort_order:count||0,is_cover:!count&&file.type.startsWith('image/')}).select('id,proxy_key,media_type').single();}
else result=await sb.from(table).update(fields).eq('id',id).select('id,proxy_key').single();
if(result.error){await fetch(`https://api.telegram.org/bot${cred.telegram_bot_token}/deleteMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:channel.channel_id,message_id:j.result.message_id})});throw new Error('MEDIA_SAVE_FAILED')};return json({ok:true,media:result.data});}catch(e){return failure(e)}});
